"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import { QueryClientProvider, QueryClient } from "@tanstack/react-query";

const inter = Inter({ subsets: ["latin"] });
const queryClient = new QueryClient();

/* export const metadata = {
  title: "My App",
  description: "Generated by Kevin",
}; */

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryClientProvider client={queryClient}>
          <div className="w-full h-screen">
            <div></div>
            {children}
          </div>
        </QueryClientProvider>
      </body>
    </html>
  );
}
